services:
  auth_service:
    build: ./services/auth_service
    container_name: securecloud-auth
    restart: unless-stopped
    environment:
      FILE_SERVICE_ADDRESS: file_service:50052
    ports:
      - "50051:50051"
    depends_on:
      - postgres

  messaging_service:
    build: ./services/messaging_service
    container_name: securecloud-messaging
    restart: unless-stopped
    ports:
      - "7002:7002"
    depends_on:
      - auth_service

  file_service:
    build: ./services/file_service
    container_name: securecloud-file
    restart: unless-stopped
    environment:
      FILE_SERVICE_STORAGE: /data/files
    volumes:
      - ./files_storage:/data/files
    ports:
      - "50052:50052"
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: securecloud-db
    restart: always
    environment:
      POSTGRES_USER: secureuser
      POSTGRES_PASSWORD: securepass
      POSTGRES_DB: securecloud
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: securecloud-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: merzoudmounir92@gmail.com
      PGADMIN_DEFAULT_PASSWORD: securepass
    ports:
      - "5050:80"
